# 保存路径, 可配合 时间, bvid, 作者 等魔法变量, 例如 /download/%author%/%time%_%name%/
# 目前支持的可以看 truelove/process/utils.py 下的 parse_save_dir 
# 不用盘符或"/"开头时, 会下载到项目根目录
# 以"/"开头, 会下载到项目盘符根目录
# 以盘符开头, 会下载到其他盘
save_dir: "download/{author}/{watch_type}/{filename}" 
log_level: "INFO" # DEBUG, INFO, WARNING, ERROR

# 某些清晰度可能需要登录或大会员
cookie: ""

download-settings:
  cover:     true
  subtitle:  false
  dm:        false
  # 间隔, 实际上代码里现在没用, 改这里也不会生效hhh
  interval: 10

plugins:
  mp4_to_mp3: false # 需要安装ffmpeg

proxies:
  # - "http://localhost:10809"
  # - "socks://localhost:10808"
